apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../base
namePrefix: dev-
#namespace: 461a32-dev
#secretGenerator:
#  - name: uri
#    envs:
#    - .secrets    
patches:
  #- patch: |-
  #    - op: add
  #      path: /spec/tasks/2/params/-
  #      value: 
  #          name: SCRIPT
  #          value: oc apply -k overlays/dev
  #  target:
  #    kind: Pipeline
  - patch: |-
      - op: add
        path: /spec/tasks/0/params/-
        value: 
            name: revision
            value: dev
    target:
      kind: Pipeline
  #- patch: |-
  #    - op: replace
  #      path: /status/ingress/0/host
  #      value: dev-ceevee-pipeline.apps.silver.devops.gov.bc.ca
  #  target:
  #    kind: Route
  #    name: event-listener
  #- patch: |-
  #    - op: replace
  #      path: /status/ingress/0/host
  #      value: dev-nrm-vulnerability-track.apps.silver.devops.gov.bc.ca
  #  target:
  #    kind: Route
  #    name: track-route
  #- patch: |-
  #    - op: replace
  #      path: /status/ingress/0/host
  #      value: dev-nrm-vulnerability-track.apps.silver.devops.gov.bc.ca
  #  target:
  #    kind: Route
  #    name: api-route
  - patch: |-
      - op: replace
        path: /spec/accessModes/0
        value: ReadWriteOnce
    target:
      kind: PersistentVolumeClaim
      name: ceevee-data