apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../base
#namePrefix: dev-
#namespace: 461a32-dev
patches:
  - patch: |-
      - op: replace
        path: /spec/tasks/1/params
        value: 
            - name: SCRIPT
              value: oc apply -k overlays/dev
            - name: VERSION
              value: latest
    target:
      kind: Pipeline


