apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../base
namePrefix: dev-
namespace: ab537b-dev
patches:
  - patch: |-
      - op: replace
        path: /spec/finally/0/params
        value: 
            - name: SCRIPT
              value: oc apply -k dev
            - name: VERSION
              value: latest
    target:
      kind: Pipeline


