apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    name: ceevee-pipeline-testt
spec:
    finally:
        - name: openshift-client
          params:
            - name: SCRIPT
              value: oc create -k dev
