apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../base
namePrefix: test-

patches:
  - patch: |-
      - op: add
        path: /spec/tasks/0/params/-
        value: 
            name: revision
            value: master
    target:
      kind: Pipeline
