---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: certbot
  template: certbot-template
metadata:
  name: certbot-dc

objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: certbot

  - apiVersion: authorization.openshift.io/v1
    kind: Role
    metadata:
      annotations:
        openshift.io/description: Least-privilege role for the Certbot job
      name: certbot
    rules:
      - apiGroups:
          - template.openshift.io
        resources:
          - processedtemplates
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - services
        verbs:
          - list
          - get
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - route.openshift.io
        resources:
          - routes
        verbs:
          - list
          - get
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - route.openshift.io
          - ""
        attributeRestrictions: null
        resources:
          - routes/custom-host
        verbs:
          - create
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    groupNames: null
    metadata:
      name: certbot
    roleRef:
      name: certbot
      kind: Role
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: certbot
