kind: ConfigMap
apiVersion: v1
metadata:
  name: oidc-configuration
data:
  ALPINE_OIDC_CLIENT_ID: changeme
  ALPINE_OIDC_TEAMS_CLAIM: groups
  ALPINE_OIDC_USERNAME_CLAIM: preferred_username
  ALPINE_OIDC_ISSUER: changeme
  ALPINE_OIDC_TEAM_SYNCHRONIZATION: "true" 
  ALPINE_OIDC_USER_PROVISIONING: "true"
  ALPINE_OIDC_ENABLED: "true"
  DOMAIN: changeme
  API_BASE_URL: changeme
  OIDC_CLIENT_ID: changeme
  OIDC_ISSUER: changeme
