kind: ConfigMap
apiVersion: v1
metadata:
  name: oidc-configuration
data:
  ALPINE_OIDC_CLIENT_ID: changeme
  ALPINE_OIDC_TEAMS_CLAIM: groups
  ALPINE_OIDC_USERNAME_CLAIM: preferred_username
  ALPINE_OIDC_ISSUER: changeme
  ALPINE_OIDC_TEAM_SYNCHRONIZATION: "true" 
  ALPINE_OIDC_USER_PROVISIONING: "true"
  ALPINE_OIDC_ENABLED: "true"
  DOMAIN: changeme
  API_BASE_URL: changeme
  OIDC_CLIENT_ID: changeme
  OIDC_ISSUER: changeme
---
kind: Template
apiVersion: v1
metadata:
  name: postgres
parameters:
- name: APP_NAME
  required: true
  value: fett
- name: DATABASE_USER
  required: true
  value: classy
- name: DATABASE_PASSWORD
  generate: expression
  from: "[\\w]{50}" #generate password when processing template
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "postgres-configuration"
  stringData:
    POSTGRES_USER: "${DATABASE_USER}"
    POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ALPINE_DATABASE_MODE: external
    ALPINE_DATABASE_URL: postgres
    ALPINE_DATABASE_DRIVER: org.postgresql.Driver
    ALPINE_DATABASE_USERNAME: "${APP_NAME}"
    ALPINE_DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    ALPINE_DATABASE_POOL_ENABLED: true
    ALPINE_DATABASE_POOL_MAX_SIZE: 20
    ALPINE_DATABASE_POOL_MIN_IDLE: 10
    ALPINE_DATABASE_POOL_IDLE_TIMEOUT: 300000
    ALPINE_DATABASE_POOL_MAX_LIFETIME: 600000